# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  release-version:
    description: 'Release Version ( PATCH | MINOR | MAJOR )'
    required: true
    default: 'PATCH'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.release-version }}