# action.yml
name: 'Action Type'
description: 'This action releases a Node Package or Merge Back a Release'
inputs:
  action-type:
    description: 'Action Type ( Release | Back )'
    required: true
    default: 'Release'
runs:
  using: node12
  main: index.js